version: '3.8'

services:
  feedback-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - feedback-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  member-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: member_db
    ports:
      - "5433:5432"
    volumes:
      - member-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  feedback-service:
    build: ./feedback-service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@feedback-db:5432/feedback_db
      - PORT=${FEEDBACK_SERVICE_PORT}
    ports:
      - "${FEEDBACK_SERVICE_PORT}:${FEEDBACK_SERVICE_PORT}"
    depends_on:
      feedback-db:
        condition: service_healthy

  member-service:
    build: ./member-service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@member-db:5432/member_db
      - PORT=${MEMBER_SERVICE_PORT}
    ports:
      - "${MEMBER_SERVICE_PORT}:${MEMBER_SERVICE_PORT}"
    depends_on:
      member-db:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    environment:
      - FEEDBACK_SERVICE_URL=http://feedback-service:${FEEDBACK_SERVICE_PORT}
      - MEMBER_SERVICE_URL=http://member-service:${MEMBER_SERVICE_PORT}
      - PORT=${GATEWAY_SERVICE_PORT}
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    depends_on:
      - feedback-service
      - member-service

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - feedback-db
      - member-db

volumes:
  feedback-db-data:
  member-db-data: 